### ISSUE TITLE
Node.js Foundation Modules Team Meeting 2020-01-08

### ISSUE THREAD

**Issue by mhdawson** [nodejs/modules#462] opened 2020-01-06 13:19 UTC
## Time

**UTC Wed 08-Jan-2020 20:00 (08:00 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Wed 08-Jan-2020 12:00 (12:00 PM) |
| US / Mountain | Wed 08-Jan-2020 13:00 (01:00 PM) |
| US / Central  | Wed 08-Jan-2020 14:00 (02:00 PM) |
| US / Eastern  | Wed 08-Jan-2020 15:00 (03:00 PM) |
| London        | Wed 08-Jan-2020 20:00 (08:00 PM) |
| Amsterdam     | Wed 08-Jan-2020 21:00 (09:00 PM) |
| Moscow        | Wed 08-Jan-2020 23:00 (11:00 PM) |
| Chennai       | Thu 09-Jan-2020 01:30 (01:30 AM) |
| Hangzhou      | Thu 09-Jan-2020 04:00 (04:00 AM) |
| Tokyo         | Thu 09-Jan-2020 05:00 (05:00 AM) |
| Sydney        | Thu 09-Jan-2020 07:00 (07:00 AM) |

Or in your local time:
* http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Modules%20Team+Meeting+2020-01-08&iso=20200108T20
* or http://www.wolframalpha.com/input/?i=08PM+UTC%2C+Jan+08%2C+2020+in+local+time

## Links

* Minutes Google Doc: <https://docs.google.com/document/d/1GyF7TWCSlA-yJubD-h4FVwOJRxaN9bLXazsC2PIb2uo/edit>

## Agenda

Extracted from **modules-agenda** labelled issues and pull requests from the **nodejs org** prior to the meeting.

### nodejs/node

* module: implement logical conditional exports ordering [#31008](https://github.com/nodejs/node/pull/31008)
* module: unflag conditional exports [#31001](https://github.com/nodejs/node/pull/31001)
* esm: The `getPackageType` utility function is not exposed [#30514](https://github.com/nodejs/node/issues/30514)

### nodejs/modules

* Conditional exports naming usability discussion [#452](https://github.com/nodejs/modules/issues/452)
* Stabilizing the resolver [#451](https://github.com/nodejs/modules/issues/451)
* unflagging in 12.x LTS [#450](https://github.com/nodejs/modules/issues/450)
* Chartering the Modules team [#412](https://github.com/nodejs/modules/issues/412)
* Loader Hooks [#351](https://github.com/nodejs/modules/issues/351)
* Patch/Instrument a module [#339](https://github.com/nodejs/modules/issues/339)

## Invited

* Modules team: @nodejs/modules

## Notes

The agenda comes from issues labelled with `modules-agenda` across **all of the repositories in the nodejs org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Joining the meeting

* link for participants: https://zoom.us/j/656987750
* For those who just want to watch: https://www.youtube.com/c/nodejs+foundation/live

**Comment by ljharb** [comment] 2020-01-06 16:53
Duplicate of nodejs/modules#461?

**Comment by hybrist** [comment] 2020-01-06 18:04
Maybe because nodejs/modules#461 started as the 7th? I'll close this one since the other has at least some discussion already.

**Closed by hybrist** 2020-01-06 18:04 UTC
